name: quiz_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_core_platform_interface: 4.6.0
  firebase_messaging: ^14.4.1 
  cloud_firestore: ^4.0.0
  firebase_storage: ^11.1.1
  equatable: ^2.0.3
  firebase_core: ^2.10.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  collection: ^1.17.0
  auto_route: ^6.3.0
  auto_route_generator: ^6.2.0
  flutter_native_splash: ^2.2.19
  flutter_keyboard_visibility: ^5.4.1
  intl: ^0.18.1
  connectivity_plus: ^3.0.6
  numberpicker: ^2.1.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
  fake_cloud_firestore: ^2.0.0
  firebase_storage_mocks: ^0.6.1


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/difficulty/
  #   - family: Pokemon
  #     fonts:
  #       - asset: assets/fonts/pokemon_pixel_font/pokemon_pixel_font.ttf

