// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPvuL62yuH8-UtvMeUpaX-HVRDLIbhAYA',
    appId: '1:561662418249:web:4b080cc9aaa0c4a8d3ce98',
    messagingSenderId: '561662418249',
    projectId: 'advmoapp-quizz-app',
    authDomain: 'advmoapp-quizz-app.firebaseapp.com',
    storageBucket: 'advmoapp-quizz-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9zaa01Zrmrxwa6JIphRi5YkF2b9gVljY',
    appId: '1:561662418249:android:949974453c7b8ea9d3ce98',
    messagingSenderId: '561662418249',
    projectId: 'advmoapp-quizz-app',
    storageBucket: 'advmoapp-quizz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOelBedX2WC1PCpipo8G4gGY8BYJ80g4',
    appId: '1:561662418249:ios:5634dec63f482c7bd3ce98',
    messagingSenderId: '561662418249',
    projectId: 'advmoapp-quizz-app',
    storageBucket: 'advmoapp-quizz-app.appspot.com',
    iosClientId: '561662418249-qtmdh4h0t0avfngtaorte4c3tljpedrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvOelBedX2WC1PCpipo8G4gGY8BYJ80g4',
    appId: '1:561662418249:ios:5634dec63f482c7bd3ce98',
    messagingSenderId: '561662418249',
    projectId: 'advmoapp-quizz-app',
    storageBucket: 'advmoapp-quizz-app.appspot.com',
    iosClientId: '561662418249-qtmdh4h0t0avfngtaorte4c3tljpedrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
